spring:
  application:
    name: fashion-e-commerce-website-backend
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fashion_sales_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

aws-s3:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ap-southeast-1
  bucket-name: fashion-e-commerce

logging:
    level:
        org:
        springframework:
            web: Trace