spring:
  application:
    name: fashion-e-commerce-website-backend
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fashion_sales_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
