-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.t_address
(
    address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city character varying(50) COLLATE pg_catalog."default",
    district character varying(50) COLLATE pg_catalog."default",
    street character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT t_address_pkey PRIMARY KEY (address_id)
    );

CREATE TABLE IF NOT EXISTS public.t_orders
(
    order_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    buyer_name character varying(100) COLLATE pg_catalog."default",
    delivery_fee numeric(10, 2),
    delivery_method smallint,
    discount_amount numeric(10, 2),
    discount_price numeric(10, 2),
    note character varying(5000) COLLATE pg_catalog."default",
    order_date timestamp(6) without time zone,
    original_amount numeric(10, 2),
    payment_method smallint,
    phone_number character varying(20) COLLATE pg_catalog."default",
    order_status smallint,
    address_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT t_orders_pkey PRIMARY KEY (order_id),
    CONSTRAINT ukogq3uebu5cw0ht4jv52v9l47n UNIQUE (address_id)
    );

CREATE TABLE IF NOT EXISTS public.t_users
(
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    date_of_birth timestamp(6) without time zone,
    email character varying(50) COLLATE pg_catalog."default",
    gender character varying(255) COLLATE pg_catalog."default",
    otp character varying(10) COLLATE pg_catalog."default",
    password character varying(1000) COLLATE pg_catalog."default",
    phone character varying(50) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default",
    username character varying(50) COLLATE pg_catalog."default",
    verify boolean,
    address_id integer,
    otp_reset character varying(10) COLLATE pg_catalog."default",
    avatar_url character varying(1000) COLLATE pg_catalog."default",
    CONSTRAINT t_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT uk1f8qpknpngd98342v0j2ceadc UNIQUE (email),
    CONSTRAINT uknfhd2g1vbh4bfdycxg2byta6a UNIQUE (address_id)
    );

CREATE TABLE IF NOT EXISTS public.t_chatbots
(
    chatbot_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    avatar_url character varying(255) COLLATE pg_catalog."default",
    message_content character varying(5000) COLLATE pg_catalog."default",
    time_stamp timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT t_chatbots_pkey PRIMARY KEY (chatbot_id)
    );

CREATE TABLE IF NOT EXISTS public.t_comments
(
    comment_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    comment_date timestamp(6) without time zone,
    rating integer,
    text_content character varying(5000) COLLATE pg_catalog."default",
    product_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT t_comments_pkey PRIMARY KEY (comment_id)
    );

CREATE TABLE IF NOT EXISTS public.t_products
(
    product_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    avg_rating numeric(10, 1),
    buy_quantity integer,
    description character varying(5000) COLLATE pg_catalog."default",
    number_of_rating integer,
    price numeric(10, 2),
    product_name character varying(500) COLLATE pg_catalog."default",
    product_status character varying(255) COLLATE pg_catalog."default",
    thumbnail character varying(500) COLLATE pg_catalog."default",
    total_quantity integer,
    brand_id integer NOT NULL,
    category_id integer NOT NULL,
    provider_id integer NOT NULL,
    CONSTRAINT t_products_pkey PRIMARY KEY (product_id)
    );

CREATE TABLE IF NOT EXISTS public.t_categories
(
    category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    category_name character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT t_categories_pkey PRIMARY KEY (category_id)
    );

CREATE TABLE IF NOT EXISTS public.t_brands
(
    brand_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    brand_name character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT t_brands_pkey PRIMARY KEY (brand_id)
    );

CREATE TABLE IF NOT EXISTS public.t_providers
(
    provider_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(50) COLLATE pg_catalog."default",
    phone_number character varying(50) COLLATE pg_catalog."default",
    provider_name character varying(500) COLLATE pg_catalog."default",
    address_id integer,
    CONSTRAINT t_providers_pkey PRIMARY KEY (provider_id),
    CONSTRAINT ukg088if922gg56026dstxt8tn4 UNIQUE (email),
    CONSTRAINT ukt2or166yv7en3l3llea3j719n UNIQUE (address_id)
    );

CREATE TABLE IF NOT EXISTS public.t_product_images
(
    product_image_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    path character varying(500) COLLATE pg_catalog."default",
    product_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT t_product_images_pkey PRIMARY KEY (product_image_id)
    );

CREATE TABLE IF NOT EXISTS public.t_product_prices
(
    product_price_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    discount integer,
    discounted_price numeric(10, 2),
    issue_date timestamp(6) without time zone,
    product_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    discounted_amount numeric(10, 2),
    expired_date timestamp(6) without time zone,
    note character varying(255) COLLATE pg_catalog."default",
    price_final numeric(10, 2),
    CONSTRAINT t_product_prices_pkey PRIMARY KEY (product_price_id)
    );

CREATE TABLE IF NOT EXISTS public.t_product_details
(
    product_detail_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    quantity integer,
    weight real,
    color_id integer NOT NULL,
    product_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    size_id integer NOT NULL,
    CONSTRAINT t_product_details_pkey PRIMARY KEY (product_detail_id)
    );

CREATE TABLE IF NOT EXISTS public.t_sizes
(
    size_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    number_size integer,
    size_type smallint,
    text_size character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT t_sizes_pkey PRIMARY KEY (size_id)
    );

CREATE TABLE IF NOT EXISTS public.t_colors
(
    color_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    color_name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT t_colors_pkey PRIMARY KEY (color_id)
    );

CREATE TABLE IF NOT EXISTS public.t_comment_medias
(
    comment_media_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    media_type character varying(255) COLLATE pg_catalog."default",
    path character varying(255) COLLATE pg_catalog."default",
    comment_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT t_comment_medias_pkey PRIMARY KEY (comment_media_id)
    );

CREATE TABLE IF NOT EXISTS public.t_notification_users
(
    notification_id integer NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT t_notification_users_pkey PRIMARY KEY (notification_id, user_id)
    );

CREATE TABLE IF NOT EXISTS public.t_notifications
(
    notification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    content character varying(255) COLLATE pg_catalog."default",
    notification_time timestamp(6) without time zone,
    CONSTRAINT t_notifications_pkey PRIMARY KEY (notification_id)
    );

CREATE TABLE IF NOT EXISTS public.t_roomchats
(
    roomchat_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id bigint NOT NULL,
    CONSTRAINT t_roomchats_pkey PRIMARY KEY (roomchat_id),
    CONSTRAINT uk8qsi1c984rll89dsnyaxx86gs UNIQUE (user_id)
    );

CREATE TABLE IF NOT EXISTS public.t_messages
(
    message_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content character varying(255) COLLATE pg_catalog."default",
    message_time timestamp(6) without time zone,
    receiver_id character varying(255) COLLATE pg_catalog."default",
    sender_id character varying(255) COLLATE pg_catalog."default",
    roomchat_id integer NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT t_messages_pkey PRIMARY KEY (message_id)
    );

CREATE TABLE IF NOT EXISTS public.t_message_medias
(
    message_media_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    media_type smallint,
    path character varying(255) COLLATE pg_catalog."default",
    message_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT t_message_medias_pkey PRIMARY KEY (message_media_id)
    );

CREATE TABLE IF NOT EXISTS public.t_tokens
(
    token_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    access_token character varying(50) COLLATE pg_catalog."default",
    expired_date timestamp(6) without time zone,
    refresh_token character varying(2000) COLLATE pg_catalog."default",
    user_id bigint NOT NULL,
    issue_date timestamp(6) without time zone,
    CONSTRAINT t_tokens_pkey PRIMARY KEY (token_id)
    );

CREATE TABLE IF NOT EXISTS public.t_user_vouchers
(
    is_used boolean,
    user_id bigint NOT NULL,
    voucher_id bigint NOT NULL,
    CONSTRAINT t_user_vouchers_pkey PRIMARY KEY (user_id, voucher_id)
    );

CREATE TABLE IF NOT EXISTS public.t_vouchers
(
    voucher_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    discount integer,
    expired_date timestamp(6) without time zone,
    max_discount_amount numeric(10, 2),
    min_order_amount numeric(10, 2),
    name character varying(500) COLLATE pg_catalog."default",
    note character varying(1000) COLLATE pg_catalog."default",
    quantity integer,
    scope smallint,
    start_date timestamp(6) without time zone,
    voucher_type smallint,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT t_vouchers_pkey PRIMARY KEY (voucher_id)
    );

CREATE TABLE IF NOT EXISTS public.t_order_vouchers
(
    order_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    voucher_id bigint NOT NULL,
    CONSTRAINT t_order_vouchers_pkey PRIMARY KEY (order_id, voucher_id)
    );

CREATE TABLE IF NOT EXISTS public.t_order_details
(
    quantity integer,
    total_amount numeric(10, 2),
    order_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    product_detail_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT t_order_details_pkey PRIMARY KEY (order_id, product_detail_id)
    );

ALTER TABLE IF EXISTS public.t_orders
    ADD CONSTRAINT fk7lup8g2h1pb1deg5fuol1l4lo FOREIGN KEY (address_id)
    REFERENCES public.t_address (address_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukogq3uebu5cw0ht4jv52v9l47n
    ON public.t_orders(address_id);


ALTER TABLE IF EXISTS public.t_orders
    ADD CONSTRAINT fkb1q2qvle7ntunntqjqufg4kp2 FOREIGN KEY (user_id)
    REFERENCES public.t_users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_users
    ADD CONSTRAINT fkrhxhwxi38l2nt1dwh9eiva697 FOREIGN KEY (address_id)
    REFERENCES public.t_address (address_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uknfhd2g1vbh4bfdycxg2byta6a
    ON public.t_users(address_id);


ALTER TABLE IF EXISTS public.t_chatbots
    ADD CONSTRAINT fk3obhx7xppgcffsr51o4dm1cx5 FOREIGN KEY (user_id)
    REFERENCES public.t_users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_comments
    ADD CONSTRAINT fk6amd1797nd7bwfacgi9ihe0un FOREIGN KEY (user_id)
    REFERENCES public.t_users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_comments
    ADD CONSTRAINT fksloi603t5nvtrdqkdecesjguk FOREIGN KEY (product_id)
    REFERENCES public.t_products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_products
    ADD CONSTRAINT fkiurgai3ief4a3h8eiaugd7hqn FOREIGN KEY (category_id)
    REFERENCES public.t_categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_products
    ADD CONSTRAINT fkofjl0m5wyn9sg819h782krvyd FOREIGN KEY (brand_id)
    REFERENCES public.t_brands (brand_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_products
    ADD CONSTRAINT fks4fwo7eatus29qmbk9cw7h0ae FOREIGN KEY (provider_id)
    REFERENCES public.t_providers (provider_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_providers
    ADD CONSTRAINT fkdy8psbo0wijtec987nnajw01x FOREIGN KEY (address_id)
    REFERENCES public.t_address (address_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukt2or166yv7en3l3llea3j719n
    ON public.t_providers(address_id);


ALTER TABLE IF EXISTS public.t_product_images
    ADD CONSTRAINT fksmjmxlqs1p6fl9fw9u0u265uj FOREIGN KEY (product_id)
    REFERENCES public.t_products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_product_prices
    ADD CONSTRAINT fkhnulkodgle7teott1y0p4a2pd FOREIGN KEY (product_id)
    REFERENCES public.t_products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_product_details
    ADD CONSTRAINT fk130d0qs90mylkkdvje73s1pg2 FOREIGN KEY (size_id)
    REFERENCES public.t_sizes (size_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_product_details
    ADD CONSTRAINT fk1fc0sdqq53b3ki3f8rw1d6k7k FOREIGN KEY (product_id)
    REFERENCES public.t_products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_product_details
    ADD CONSTRAINT fkefq1fqxmtonxp5jwdl300h1yl FOREIGN KEY (color_id)
    REFERENCES public.t_colors (color_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_comment_medias
    ADD CONSTRAINT fkcd72cx5ay1h5befi4v0374p0j FOREIGN KEY (comment_id)
    REFERENCES public.t_comments (comment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_notification_users
    ADD CONSTRAINT fk6b16s1tj26lbhqg7uoubm3r5h FOREIGN KEY (user_id)
    REFERENCES public.t_users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_notification_users
    ADD CONSTRAINT fkhvb0t4yj8sjm66n5cqf8m2yf2 FOREIGN KEY (notification_id)
    REFERENCES public.t_notifications (notification_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_roomchats
    ADD CONSTRAINT fkgcm9eqvsbr3sh9xxnav41s7bm FOREIGN KEY (user_id)
    REFERENCES public.t_users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk8qsi1c984rll89dsnyaxx86gs
    ON public.t_roomchats(user_id);


ALTER TABLE IF EXISTS public.t_messages
    ADD CONSTRAINT fkdhammrxrcwisi8ge4a057dygv FOREIGN KEY (roomchat_id)
    REFERENCES public.t_roomchats (roomchat_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_message_medias
    ADD CONSTRAINT fklcj1pe1xtnn6qpoklxjmtyj5k FOREIGN KEY (message_id)
    REFERENCES public.t_messages (message_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_tokens
    ADD CONSTRAINT fk4yapf70j8ywq6xye5ypmr4a9g FOREIGN KEY (user_id)
    REFERENCES public.t_users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_user_vouchers
    ADD CONSTRAINT fk3irv8pr4vuycw18ma1fxvf3s9 FOREIGN KEY (voucher_id)
    REFERENCES public.t_vouchers (voucher_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_user_vouchers
    ADD CONSTRAINT fkp4a9o6o9a2msb0sfqyqgol0og FOREIGN KEY (user_id)
    REFERENCES public.t_users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_order_vouchers
    ADD CONSTRAINT fk2wk2t4mtc788i41031mtnpftk FOREIGN KEY (voucher_id)
    REFERENCES public.t_vouchers (voucher_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_order_vouchers
    ADD CONSTRAINT fkjmq6xjtsiioxs9wxtv1eveykk FOREIGN KEY (order_id)
    REFERENCES public.t_orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.t_order_details
    ADD CONSTRAINT fkecks6af8fg4au77s6j576dce6 FOREIGN KEY (order_id)
    REFERENCES public.t_orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

END;